[tool.mypy]
strict = true

[tool.flake8]
max-line-length = 88

[tool.pytest.ini_options]
addopts = "-s"
pythonpath = ["tests", "src/django_project"]
DJANGO_SETTINGS_MODULE = "django_project.project.settings.dev"
